title: Eisa Mahyari, Ph.D.
description: Computational Biology | Machine Learning | Spatial Omics | Translational Research

remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache

# Optional defaults
minimal_mistakes_skin: "air"  # "default", "air", "contrast", etc.
markdown: kramdown
